global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: fantasy-dota
    static_configs:
      - targets: [ 'fantasy-dota:8080' ]
  - job_name: grafana
    static_configs:
      - targets: [ 'grafana:3000' ]
  - job_name: postgres
    static_configs:
      - targets: [ 'pg-exporter:9187' ]
