openapi: 3.0.3

info:
  title: Fantasy Dota App
  version: 1.0.0

paths:
  /example:
    get:
      summary: Example GET handler.
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
    post:
      summary: Example POST handler.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleObject'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
components:
  schemas:
    ExampleResponse:
      type: array
      items:
        $ref: '#/components/schemas/ExampleObject'
    ExampleObject:
      type: object
      properties:
        name:
          type: string
      required:
        - name
